function [fitresult, gof] = createFits(cdate, pop)
%CREATEFITS(CDATE,POP)
%  Create fits.
%
%  Data for 'pop_poly2' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'pop_poly3' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'pop_poly4' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'pop_poly5' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'pop_poly6' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'pop_exp1' fit:
%      X Input : cdate
%      Y Output: pop
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Oct-2021 07:36:45

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 6, 1 );
gof = struct( 'sse', cell( 6, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'pop_poly2'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'pop_poly2' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'pop vs. cdate', 'pop_poly2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'cdate', 'Interpreter', 'none' );
ylabel( 'pop', 'Interpreter', 'none' );
grid on

%% Fit: 'pop_poly3'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'pop_poly3' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'pop vs. cdate', 'pop_poly3', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'cdate', 'Interpreter', 'none' );
ylabel( 'pop', 'Interpreter', 'none' );
grid on

%% Fit: 'pop_poly4'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'pop_poly4' );
h = plot( fitresult{3}, xData, yData );
legend( h, 'pop vs. cdate', 'pop_poly4', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'cdate', 'Interpreter', 'none' );
ylabel( 'pop', 'Interpreter', 'none' );
grid on

%% Fit: 'pop_poly5'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'pop_poly5' );
h = plot( fitresult{4}, xData, yData );
legend( h, 'pop vs. cdate', 'pop_poly5', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'cdate', 'Interpreter', 'none' );
ylabel( 'pop', 'Interpreter', 'none' );
grid on

%% Fit: 'pop_poly6'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly6' );

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'pop_poly6' );
h = plot( fitresult{5}, xData, yData );
legend( h, 'pop vs. cdate', 'pop_poly6', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'cdate', 'Interpreter', 'none' );
ylabel( 'pop', 'Interpreter', 'none' );
grid on

%% Fit: 'pop_exp1'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [9.04156595494883e-15 0.0191475089826057];

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'pop_exp1' );
h = plot( fitresult{6}, xData, yData );
legend( h, 'pop vs. cdate', 'pop_exp1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'cdate', 'Interpreter', 'none' );
ylabel( 'pop', 'Interpreter', 'none' );
grid on


